# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: install
    workingDir: SignalRWebPack/SignalRWebPack
  displayName: 'npm install'

# - task: DotNetCoreCLI@2
#   displayName: Build
#   inputs:
#     projects: ' SignalRWebPack/SignalRWebPack/SignalRWebPack.csproj'
#     arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: test
    workingDirectory: $(workingDirectory)
    projects: 'SignalRWebPack/SignalRWebPack.Test/SignalRWebPack.Test.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  displayName: 'Publish functional tests'
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(build.ArtifactStagingDirectory)/*.trx'

# - task: DotNetCoreCLI@2
#   displayName: Publish
#   inputs:
#     command: publish
#     publishWebProjects: true
#     projects: 'SignalRWebPack/SignalRWebPack/SignalRWebPack.csproj'
#     arguments: '--configuration $(BuildConfiguration) --output $(build.ArtifactStagingDirectory)'
#     zipAfterPublish: true

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifact'
#   inputs:
#     PathtoPublish: $(Build.ArtifactStagingDirectory)
